<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="FinanceDashboard\Assets\Icons\" />
    <Folder Include="FinanceDashboard\Assets\Styles\" />
    <Folder Include="FinanceDashboard\Models\" />
    <Folder Include="FinanceDashboard\Views\" />
    <Folder Include="FinanceDashboard\ViewModels\" />
  </ItemGroup>

</Project>
